name: Docker

on:
  push:
  schedule:
    - cron: 0 0 * * 0

permissions:
  packages: write

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ env.ID }}
    steps:
      - name: Get id
        id: id
        run: |
          VERSIONS=$(gh api users/81f9db2ec2/packages/container/danmakus-core/versions)
          if [ $? -ne 0 || -z "$VERSIONS" ]; then
            echo "gh api failed or no versions found, skipping"
            exit 1
          fi
          echo "ID=$(echo "$VERSIONS" | jq .[0].id)" >>"$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ github.token }}

  cmp:
    needs: pre
    uses: WaterLemons2k/.github/.github/workflows/compare.yml@main
    with:
      new: ${{ needs.pre.outputs.id }}

  git:
    needs: cmp
    if: needs.cmp.outputs.changed == 'true'
    uses: WaterLemons2k/.github/.github/workflows/git.yml@main
    with:
      run: |
        VERSION=${{ needs.cmp.outputs.version }}
      commit_message: 'chore: update danmakus-core'

  docker:
    needs: [cmp, git]
    if: needs.cmp.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v6
        with:
          repository: 81f9db2ec2/danmakus-client

      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: docker

      - name: Apply patch
        run: git apply docker/patches/0001-fix-eacces.patch

      - name: Get version
        id: ver
        run: echo "version=$(jq -r .version danmakus-core/package.json)" >>"$GITHUB_OUTPUT"

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/wl2k/danmakus-core
          tags: |
            type=raw,value=latest
            type=raw,value=v${{ steps.ver.outputs.version }}
            type=sha

      - name: Login to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./danmakus-core
          push: true
          tags: ${{ steps.meta.outputs.tags }}
